[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "onthespot"  # Replace with your package's name
version = "0.5.0"  # Replace with your version
description = "onthespot project"  # Replace with your description
