name: Build

on:  
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  
  workflow_dispatch:


jobs:
  # Windows Build
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
        with:
          name: windows_binary
          path: dist
            
  # Linux Build
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf fuse libfuse2 wget
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install build

      - name: Make Build Scripts Executable
        run: |
          chmod +x scripts/build_linux.sh

      - name: Run Linux Build Script
        run: sh scripts/build_linux.sh
        shell: bash
      
      - name: Upload Artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
        with:
          name: linux_binary
          path: dist
      
      - name: Merge PR
        if: ${{ github.event.pull_request.mergeable == true && github.event.pull_request.merged == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }}
