name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  
  workflow_dispatch:


jobs:
  # Windows Build
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

  # Linux Build
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf fuse libfuse2 wget
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install build

      - name: Make Build Scripts Executable
        run: |
          chmod +x scripts/build_linux.sh

      - name: Run Linux Build Script
        run: sh scripts/build_linux.sh
        shell: bash

      - name: Create Linux tar.gz
        run: |
          cd dist
          tar -czvf onthespot_linux.tar.gz onthespot_linux

  #         asset_content_type: application/x-apple-diskimage

